Repository woowa-coupons/woowa-coupons, pull requests merged in 2023-10, with the labels that each got.

#2 [BE][chore] 프로젝트 초기 세팅
  be/coupons/.gitignore
  be/coupons/build.gradle
  be/coupons/gradle/wrapper/gradle-wrapper.jar
  be/coupons/gradle/wrapper/gradle-wrapper.properties
  be/coupons/gradlew
  be/coupons/gradlew.bat
  be/coupons/settings.gradle
  be/coupons/src/main/java/woowa/coupons/CouponsApplication.java
  be/coupons/src/test/java/woowa/coupons/CouponsApplicationTests.java
Labels: 🧑🏻‍💻 backend, 🛠 setting

#4 [BE] [chore] 스키마 작성 & docker-compose 파일 작성
  be/coupons/.gitignore
  be/coupons/src/main/resources/application-local.yml
  be/coupons/src/main/resources/application.yml
  be/coupons/src/main/resources/docker-compose.yml
  be/coupons/src/main/resources/scehma.sql
Labels: 🧑🏻‍💻 backend, 🛠 setting

#6 [BE] [feat] 초기 엔티티 클래스 작성
  be/coupons/settings.gradle
  be/promotion/.gitignore
  be/promotion/build.gradle
  be/promotion/gradle/wrapper/gradle-wrapper.jar
  be/promotion/gradle/wrapper/gradle-wrapper.properties
  be/promotion/gradlew
  be/promotion/gradlew.bat
  be/promotion/settings.gradle
  be/promotion/src/main/java/woowa/promotion/CouponsApplication.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/domain/Admin.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon/domain/Coupon.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon/domain/CouponType.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/CouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/domain/ProgressStatus.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/domain/Promotion.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_history/PromotionHistory.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/MemberType.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/PromotionOption.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option_coupon/domain/PromotionOptionCoupon.java
  be/promotion/src/main/java/woowa/promotion/app/member/domain/Member.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/domain/MemberCoupon.java
  be/promotion/src/main/java/woowa/promotion/app/order/domain/Order.java
  be/promotion/src/main/java/woowa/promotion/global/config/JpaAuditConfig.java
  be/promotion/src/main/java/woowa/promotion/global/domain/audit/AuditingFields.java
  be/promotion/src/main/resources/application-local.yml
  be/promotion/src/main/resources/application.yml
  be/promotion/src/main/resources/docker-compose.yml
  be/promotion/src/main/resources/scehma.sql
  be/promotion/src/test/java/woowa/promotion/CouponsApplicationTests.java
Labels: ✨ feature, 🧑🏻‍💻 backend

#8 [BE][chore] CI/CD 설정
  .github/workflows/workflow.yml
  Dockerfile
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#10 [BE] [test] RestDocs, Test Container, Jacoco 환경설정
  be/promotion/build.gradle
  be/promotion/src/main/resources/application-test.yml
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/resources/schema.sql
Labels: 🧑🏻‍💻 backend, ✅ test

#16 [FE][chore] FE 개발 환경 세팅
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/main.tsx
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: 🧑🏻‍💻 frontend, 🛠 setting

#17 [BE][feat] 사용자 로그인/회원가입
  be/promotion/src/main/java/woowa/promotion/app/member/application/MemberService.java
  be/promotion/src/main/java/woowa/promotion/app/member/application/dto/request/SignInServiceRequest.java
  be/promotion/src/main/java/woowa/promotion/app/member/application/dto/request/SignUpServiceRequest.java
  be/promotion/src/main/java/woowa/promotion/app/member/application/dto/response/SignInServiceResponse.java
  be/promotion/src/main/java/woowa/promotion/app/member/domain/Member.java
  be/promotion/src/main/java/woowa/promotion/app/member/infrastructure/MemberRepository.java
  be/promotion/src/main/java/woowa/promotion/app/member/presentation/MemberController.java
  be/promotion/src/main/java/woowa/promotion/app/member/presentation/dto/request/SignInRequest.java
  be/promotion/src/main/java/woowa/promotion/app/member/presentation/dto/request/SignUpRequest.java
  be/promotion/src/main/java/woowa/promotion/global/config/SecurityConfig.java
  be/promotion/src/main/java/woowa/promotion/global/domain/jwt/JwtProvider.java
  be/promotion/src/main/java/woowa/promotion/global/exception/ApiException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/CustomException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/GlobalExceptionHandler.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/JwtException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/MemberException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/response/ErrorCode.java
  be/promotion/src/main/java/woowa/promotion/global/exception/response/ErrorResponse.java
  be/promotion/src/main/java/woowa/promotion/global/security/hash/PasswordEncoder.java
  be/promotion/src/main/java/woowa/promotion/global/security/hash/SHA256.java
  be/promotion/src/main/resources/scehma.sql
  be/promotion/src/test/java/woowa/promotion/CouponsApplicationTests.java
  be/promotion/src/test/java/woowa/promotion/acceptance/MemberAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/acceptance/SupportRepository.java
  be/promotion/src/test/java/woowa/promotion/app/member/application/MemberServiceTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/fixture/UserFixture.java
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/util/ApplicationTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#21 [BE][test] 인수테스트 @Transactional 제거
  be/promotion/src/main/java/woowa/promotion/global/exception/ApiException.java
  be/promotion/src/main/java/woowa/promotion/global/security/hash/SHA256.java
  be/promotion/src/test/java/woowa/promotion/acceptance/MemberAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/acceptance/SupportRepository.java
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/resources/schema.sql
Labels: 🧑🏻‍💻 backend, ✅ test

#32 [BE] [feat] 관리자 로그인
  be/promotion/src/docs/asciidoc/admin.adoc
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/AuthService.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/dto/request/SignInServiceRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/dto/request/SignupServiceRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/dto/response/SignInServiceResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/domain/Admin.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/infrastructure/AdminRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/AuthController.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/dto/request/SignInRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/dto/response/SignInResponse.java
  be/promotion/src/main/java/woowa/promotion/global/domain/jwt/JwtProvider.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/AdminException.java
  be/promotion/src/test/java/woowa/promotion/acceptance/AdminAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/acceptance/MemberAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/admin/application/AuthServiceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/documentation/AuthDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/app/member/application/MemberServiceTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/global/domain/jwt/JwtProviderTest.java
  be/promotion/src/test/java/woowa/promotion/global/security/hash/SHA256Test.java
  be/promotion/src/test/java/woowa/promotion/global/util/HttpAuthorizationUtilTest.java
  be/promotion/src/test/java/woowa/promotion/util/DocumentationTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#34 [BE][fix] 중복 회원 가입이 가능하며, 기존 회원 로그인이 불가능한 이슈 수정
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/AuthService.java
Labels: 🚨 bug, 🧑🏻‍💻 backend

#36 [BE][fix] 인가 ArgumentResolver가 제대로 작동하지 않던 이슈 해결
  be/promotion/src/main/java/woowa/promotion/global/resolver/AuthArgumentResolver.java
Labels: 🚨 bug, 🧑🏻‍💻 backend

#37 [BE][feat] AuthInterceptor에 인증된 회원 객체를 담는 로직 구현
  be/promotion/src/main/java/woowa/promotion/global/interceptor/AuthInterceptor.java
  be/promotion/src/main/java/woowa/promotion/global/service/AuthService.java
Labels: ✨ feature, 🧑🏻‍💻 backend

#38 [BE][feat] 쿠폰 그룹 생성 기능 구현
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/AdminService.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/AuthController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon/domain/Coupon.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon/domain/CouponType.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon/infrastructure/CouponRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/application/CouponGroupService.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/CouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/infrastructure/CouponGroupRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/CouponGroupCreateRequest.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/CouponException.java
  be/promotion/src/main/resources/schema.sql
  be/promotion/src/test/java/woowa/promotion/acceptance/CouponGroupAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/admin/application/AdminServiceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/documentation/AuthDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/util/DocumentationTest.java
  be/promotion/src/test/resources/schema.sql
Labels: ✨ feature, 🧑🏻‍💻 backend

#41 [FE][style] 디자인 시스템 적용
  fe/index.html
  fe/public/BI.png
  fe/src/main.tsx
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/base/Color.ts
  fe/src/styles/base/Font.ts
  fe/src/styles/base/Object.ts
  fe/src/styles/theme.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: 🧑🏻‍💻 frontend

#42 [BE][feat] 쿠폰그룹 목록 조회
  be/promotion/src/docs/asciidoc/couponGroup.adoc
  be/promotion/src/docs/asciidoc/index.adoc
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/application/CouponGroupService.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/CouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/infrastructure/CouponGroupRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/response/CouponGroupsResponse.java
  be/promotion/src/main/java/woowa/promotion/global/domain/page/CustomPage.java
  be/promotion/src/main/resources/application-local.yml
  be/promotion/src/main/resources/application-test.yml
  be/promotion/src/test/java/woowa/promotion/acceptance/AdminAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/acceptance/CouponGroupAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/admin/application/AdminServiceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/coupon_group/application/CouponGroupServiceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/documentation/CouponGroupDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/util/DocumentationTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#46 [FE][add] SVGR 라이브러리 적용
  fe/package-lock.json
  fe/package.json
  fe/tsconfig.json
  fe/vite.config.ts
Labels: 🧑🏻‍💻 frontend, 🛠 setting

#40 [BE][feat] 프로모션 생성 및 조회 API
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/CouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/PromotionService.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/dto/request/PromotionRegisterRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/dto/response/PromotionDetailResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/dto/response/PromotionListResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/domain/Promotion.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/infrastructure/PromotionRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/presentation/PromotionController.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/MemberType.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/PromotionOption.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/infrastructure/PromotionOptionRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option_coupon_group/domain/PromotionOptionCouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option_coupon_group/infrastructure/PromotionOptionCouponGroupRepository.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/CouponGroupException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/MemberTypeException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/PromotionException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/PromotionOptionException.java
  be/promotion/src/main/resources/schema.sql
  be/promotion/src/test/java/woowa/promotion/acceptance/PromotionAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/promotion/application/PromotionServiceTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/CouponGroupFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/fixture/PromotionFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/PromotionOptionFixture.java
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/resources/schema.sql
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#47 [FE][feat] Icon 컴포넌트
  fe/src/assets/icons/calendar.svg
  fe/src/assets/icons/chart.svg
  fe/src/assets/icons/chevron-down.svg
  fe/src/assets/icons/chevron-left.svg
  fe/src/assets/icons/chevron-right.svg
  fe/src/assets/icons/chevron-up.svg
  fe/src/assets/icons/dots.svg
  fe/src/assets/icons/edit.svg
  fe/src/assets/icons/grid.svg
  fe/src/assets/icons/home.svg
  fe/src/assets/icons/plus.svg
  fe/src/assets/icons/refresh.svg
  fe/src/assets/icons/search.svg
  fe/src/assets/icons/trash.svg
  fe/src/assets/icons/x.svg
  fe/src/components/common/Icon/Icon.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#48 [BE][feat] 쿠폰그룹 간단 목록 조회
  be/promotion/src/docs/asciidoc/couponGroup.adoc
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/application/CouponGroupService.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/infrastructure/CouponGroupRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/response/CouponGroupSimpleResponse.java
  be/promotion/src/test/java/woowa/promotion/acceptance/CouponGroupAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/coupon_group/application/CouponGroupServiceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/documentation/CouponGroupDocumentationTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#54 [BE][feat] 회원 프로모션 목록 조회
  be/promotion/src/docs/asciidoc/appPromotion.adoc
  be/promotion/src/docs/asciidoc/index.adoc
  be/promotion/src/main/java/woowa/promotion/admin/promotion/infrastructure/PromotionRepository.java
  be/promotion/src/main/java/woowa/promotion/app/promotion/application/AppPromotionService.java
  be/promotion/src/main/java/woowa/promotion/app/promotion/presentation/AppPromotionController.java
  be/promotion/src/main/java/woowa/promotion/app/promotion/presentation/dto/AppPromotionResponse.java
  be/promotion/src/test/java/woowa/promotion/acceptance/AppPromotionAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/app/documentation/PromotionDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/app/promotion/application/AppPromotionServiceTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/PromotionFixture.java
  be/promotion/src/test/java/woowa/promotion/util/DocumentationTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#53 [BE][feat] 쿠폰그룹 상세 조회
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/application/CouponGroupService.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/infrastructure/CouponGroupRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/response/CouponGroupDetailResponse.java
  be/promotion/src/test/java/woowa/promotion/acceptance/CouponGroupAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/coupon_group/application/CouponGroupServiceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/documentation/CouponGroupDocumentationTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend, ✅ test

#56 [BE][refactor] ERD 변경사항 반영
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/CouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/Type.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/CouponGroupCreateRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/PromotionOption.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/BadRequestException.java
  be/promotion/src/main/resources/schema.sql
  be/promotion/src/test/java/woowa/promotion/fixture/CouponGroupFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/resources/schema.sql
Labels: 🧑🏻‍💻 backend

#59 [FE][FEAT] 상태 배지 컴포넌트 구현
  fe/src/components/common/statusBadge/StateBadge.styles.ts
  fe/src/components/common/statusBadge/StateBadge.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#60 [FE][FEAT] 커스텀 버튼 컴포넌트 구현
  fe/src/components/common/button/CustomButton.style.ts
  fe/src/components/common/button/CustomButton.tsx
  fe/src/components/common/button/CustomButtonType.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#61 [FE][FEAT] 사이드바 컴포넌트 구현
  fe/src/components/common/sideBar/SideBar.style.ts
  fe/src/components/common/sideBar/SideBar.tsx
  fe/src/components/common/sideBar/SideBarItem.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#62 [FE][FEAT] 서치바 컴포넌트 구현
  fe/src/components/common/searchBar/SearchBar.style.ts
  fe/src/components/common/searchBar/SearchBar.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#64 [BE][refactor] 랜덤발급 여부 로직 수정
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/domain/CouponGroup.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/CouponGroupCreateRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/response/CouponGroupDetailResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/response/CouponGroupsResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/PromotionService.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/dto/request/PromotionRegisterRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/dto/response/PromotionDetailResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/PromotionOption.java
  be/promotion/src/main/resources/schema.sql
  be/promotion/src/test/java/woowa/promotion/acceptance/PromotionAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/admin/documentation/CouponGroupDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/admin/promotion/application/PromotionServiceTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/CouponGroupFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/fixture/PromotionOptionFixture.java
  be/promotion/src/test/resources/schema.sql
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#65 [BE][chore] CICD 배포 환경 구성
  .github/workflows/workflow.yml
  docker-compose-deploy.yml
Labels: 🧑🏻‍💻 backend

#71 [FE][feat] 버튼 컴포넌트 구현
  fe/src/components/common/Button/Button.styles.ts
  fe/src/components/common/Button/Button.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#76 [FE][feat] Layout 컴포넌트
  fe/src/components/common/Layout/Layout.styles.ts
  fe/src/components/common/Layout/Layout.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#77 [FE][feat] Header 컴포넌트
  fe/src/components/Header/Header.styles.ts
  fe/src/components/Header/Header.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#79 [FE][feat] 프로모션 리스트 페이지
  fe/src/pages/PromotionPage/PromotionPage.styles.ts
  fe/src/pages/PromotionPage/PromotionPage.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#81 [FE][feat] 프로모션 상세 페이지
  fe/src/pages/PromotionDetailPage/PromotionDetailPage.styles.ts
  fe/src/pages/PromotionDetailPage/PromotionDetailPage.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#83 [FE][feat] 프로모션 추가 페이지
  fe/src/pages/PromotionAddPage/PromotionAddPage.styles.ts
  fe/src/pages/PromotionAddPage/PromotionAddPage.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#85 [FE][feat] 스타트 페이지
  fe/src/pages/StartPage/StartPage.styles.ts
  fe/src/pages/StartPage/StartPage.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#87 [FE][feat] 에러 페이지
  fe/src/pages/ErrorPage/ErrorPage.styles.ts
  fe/src/pages/ErrorPage/ErrorPage.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#89 [FE][feat] SideBar 컴포넌트
  fe/src/components/SideBar/SideBar.styles.ts
  fe/src/components/SideBar/SideBar.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#91 [FE][feat] Promotion Table 컴포넌트
  fe/src/components/PromotionTable/PromotionTable.fallback.tsx
  fe/src/components/PromotionTable/PromotionTable.styles.ts
  fe/src/components/PromotionTable/PromotionTable.tsx
Labels: ✨ feature, 🧑🏻‍💻 frontend

#70 [FE][feat] 쿠폰 등록 페이지 구현
  fe/src/components/common/button/CustomButton.tsx
  fe/src/components/coupon/CouponGroup.style.ts
  fe/src/components/coupon/CouponGroupCard.tsx
  fe/src/components/coupon/CouponType.tsx
  fe/src/components/coupon/inputGroup/DateInputGroup.tsx
  fe/src/components/coupon/inputGroup/InputGroup.style.tsx
  fe/src/components/coupon/inputGroup/InputGroupType.ts
  fe/src/components/coupon/inputGroup/SelectInputGroup.tsx
  fe/src/components/coupon/inputGroup/TextInputGroup.tsx
  fe/src/components/coupon/registrationGroup/CouponRegistrationGroup.style.ts
  fe/src/components/coupon/registrationGroup/CouponRegistrationGroup.tsx
  fe/src/components/coupon/registrationGroup/CouponRegistrationItem.tsx
  fe/src/components/coupon/registrationGroup/RegistrationInputBox.tsx
  fe/src/components/coupon/registrationGroup/RegistrationViewBox.tsx
  fe/src/components/coupon/useCoupons.ts
  fe/src/hooks/useInput.ts
Labels: ✨ feature, 🧑🏻‍💻 frontend

#93 [FE][style] 아이콘 이미지 수정
  fe/src/assets/icons/calendar.svg
  fe/src/assets/icons/chart.svg
  fe/src/assets/icons/edit.svg
  fe/src/assets/icons/filter.svg
  fe/src/assets/icons/plus.svg
  fe/src/assets/icons/refresh.svg
  fe/src/assets/icons/search.svg
  fe/src/assets/icons/trash.svg
Labels: ✨ feature, 🧑🏻‍💻 frontend

#66 [BE][feat] 쿠폰 발급
  be/promotion/src/main/java/woowa/promotion/admin/coupon/domain/Coupon.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon/infrastructure/CouponRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/dto/request/PromotionRegisterRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/domain/PromotionOption.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option_coupon_group/infrastructure/PromotionOptionCouponGroupRepository.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/application/MemberCouponService.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/application/condition/LastOrderCondition.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/application/condition/MemberTypeCondition.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/application/condition/PromotionOptionCondition.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/domain/MemberCoupon.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/infrastructure/MemberCouponRepository.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/presentation/AppCouponController.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/presentation/dto/CouponIssueRequest.java
  be/promotion/src/main/java/woowa/promotion/app/order/domain/Order.java
  be/promotion/src/main/java/woowa/promotion/app/order/infrastructure/OrderRepository.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/CouponException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/CouponGroupException.java
  be/promotion/src/main/java/woowa/promotion/global/exception/domain/PromotionOptionException.java
  be/promotion/src/test/java/woowa/promotion/acceptance/MemberCouponAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/app/documentation/MemberCouponDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/fixture/CouponFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/CouponGroupFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/FixtureFactory.java
  be/promotion/src/test/java/woowa/promotion/fixture/PromotionFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/PromotionOptionFixture.java
  be/promotion/src/test/java/woowa/promotion/fixture/UserFixture.java
  be/promotion/src/test/java/woowa/promotion/util/AcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/util/DocumentationTest.java
  be/promotion/src/test/resources/saveScenarioA.sql
  be/promotion/src/test/resources/saveScenarioB.sql
Labels: ✨ feature, 🧑🏻‍💻 backend
