Repository woowa-coupons/woowa-coupons, pull requests merged in 2023-11, with the labels that each got.

#102 [BE][fix] 쿠폰을 가져올 때 비관적 락 걸기
  be/promotion/src/main/java/woowa/promotion/admin/coupon/infrastructure/CouponRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option/infrastructure/PromotionOptionRepository.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/application/MemberCouponService.java
Labels: 🧑🏻‍💻 backend, ✅ test

#103 [BE][feat] synchronized 키워드를 이용해 동시성 문제 해결
  be/promotion/src/main/java/woowa/promotion/admin/coupon/infrastructure/CouponRepository.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/application/SynchronizedOuter.java
  be/promotion/src/main/java/woowa/promotion/app/member_coupon/presentation/AppCouponController.java
  be/promotion/src/test/java/woowa/promotion/app/member_coupon/application/MemberCouponServiceTest.java
  be/promotion/src/test/java/woowa/promotion/application/app/MemberCouponTest.java
Labels: ✨ feature, 🧑🏻‍💻 backend

#138 [BE][fix] 페이징 관련에러 수정
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/test/java/woowa/promotion/acceptance/admin/CouponGroupAcceptanceTest.java
Labels: 🚨 bug, 🧑🏻‍💻 backend

#140 [BE][refactor] admin 패키지 리팩토링(메서드 분리, 패키지 이름 수정)
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/AdminService.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/dto/request/SignInServiceRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/dto/request/SignupServiceRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/application/dto/response/SignInServiceResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/AuthController.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/dto/request/SignupRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/admin/presentation/dto/response/SignInResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/application/AdminAuthService.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/domain/Admin.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/infrastructure/AdminRepository.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/presentation/AdminAuthController.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/presentation/dto/request/SignInRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/presentation/dto/request/SignUpRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/auth/presentation/dto/response/SignInResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/application/CouponGroupService.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/CouponGroupController.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/request/CouponGroupCreateRequest.java
  be/promotion/src/main/java/woowa/promotion/admin/coupon_group/presentation/dto/response/CouponGroupDetailResponse.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion/application/PromotionService.java
  be/promotion/src/main/java/woowa/promotion/admin/promotion_option_coupon_group/domain/PromotionOptionCouponGroup.java
  be/promotion/src/main/java/woowa/promotion/global/resolver/AuthArgumentResolver.java
  be/promotion/src/main/java/woowa/promotion/global/service/AuthService.java
  be/promotion/src/test/java/woowa/promotion/acceptance/admin/CouponGroupAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/acceptance/admin/PromotionAcceptanceTest.java
  be/promotion/src/test/java/woowa/promotion/application/admin/admin/application/AdminAuthServiceTest.java
  be/promotion/src/test/java/woowa/promotion/documentation/AuthDocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/util/DocumentationTest.java
  be/promotion/src/test/java/woowa/promotion/util/fixture/FixtureFactory.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor
